GET http://localhost:5000/api/users
###
GET http://localhost:5000/api/sushibars/5ffcfe2636a1d960b4e44425


###
POST http://localhost:5000/api/sushibars
Content-Type: application/json

{
    "name": "reyadh",
    "location": "NY",
    "menu" : "Sushi",
    "features": "A/C, Reservations, Buffet"
}

###
DELETE http://localhost:5000/api/sushibars/5ffd2f8d36a1d960b4e44428

###
PATCH  http://localhost:5000/api/sushibars/5ffcfe2636a1d960b4e44425
Content-Type: application/json

{
    "name": "Watami",
    "location": "Cape Girardeau",
    "menu" : "Sushi",
    "features": "A/C"
}

###

POST http://localhost:5000/api/ratings
Content-Type: application/json

{
    "name": "testUser",
    "email": "test@gmail.com",
    "password" : "test123"
}

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "GlennSenevi",
    "email": "glenn@gmail.com",
    "password": "12345"
}

###

GET http://localhost:5000/api/users/


###
Token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMGM5ZmZlMmE0MGM2ZDE1NGRkY2EzZiIsImlhdCI6MTYxMTQ0MDEyNiwiZXhwIjoxNjExNDQzNzI2fQ.nIt68dYjcNFB_OzfOduwj-RCf2ej11AeKeyBgS7bz6A